### ISSUE TITLE
crash:  Cannot form pointer to group type

### ISSUE THREAD

**Issue by little-dude** [jparyani/pycapnp#100]
Hi,

First, thank you for making pycapnp.

I have this in my schemas:

```
struct Field {
    value     @0 :Data;
    mode      @1 :Text;
    step      @2 :Data;
    mask      @3 :Data;
    count     @4 :UInt64;
}

struct Protocol {
    union {
        ethernet2 :group {
            source       @0  :Field = (mode = "fixed", mask = 0x"FF FF FF FF FF FF", value = 0x"00 00 00 00 00 00");
            destination  @1  :Field = (mode = "fixed", mask = 0x"FF FF FF FF FF FF", value = 0x"FF FF FF FF FF FF");
            ethernetType @2  :Field = (mode = "fixed", mask = 0x"FF FF",             value = 0x"08 00")            ;
        }
        ipv4 :group {
            version      @3  :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"04")               ;
            ihl          @4  :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"05")               ;
            tos          @5  :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"00")               ;
            length       @6  :Field = (mode = "auto" , mask = 0x"FF",                value = 0x"00")               ;
            id           @7  :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"00")               ;
            flags        @8  :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"00")               ;
            fragOffset   @9  :Field = (mode = "fixed", mask = 0x"FF FF",             value = 0x"00 00")            ;
            ttl          @10 :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"FF")               ;
            protocol     @11 :Field = (mode = "auto" , mask = 0x"FF",                value = 0x"00")               ;
            checksum     @12 :Field = (mode = "auto" , mask = 0x"FF",                value = 0x"00")               ;
            srcip        @13 :Field = (mode = "fixed", mask = 0x"FF FF FF FF",       value = 0x"00 00 00 00")      ;
            dstip        @14 :Field = (mode = "fixed", mask = 0x"FF FF FF FF",       value = 0x"FF FF FF FF")      ;
            options      @15 :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"00")               ;
            padding      @16 :Field = (mode = "fixed", mask = 0x"FF",                value = 0x"00")               ;
        }
    }
}
```

It loads correctly, but I cannot create an `Ethernet2` message:

```
In [1]: import capnp ; import main_capnp

In [2]: msg = main_capnp.Protocol.Ethernet2.new_message()
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  src/capnp/dynamic.c++:1810: failed: expected !schema.getProto().getStruct().getIsGroup(); Cannot form pointer to group type.
stack: 0x7ffa22489f09 0x7ffa2248dedd 0x7ffa2293695c 0x7ffa22944100 0x7ffa2313f704 0x7ffa2312c6d2 0x7ffa2312cca2 0x7ffa296a4609 0x7ffa2965d0da 0x7ffa297164bc 0x7ffa2971d9e2 0x7ffa2971dac3 0x7ffa2971daeb 0x7ffa2971202d 0x7ffa296a45e9 0x7ffa2971c5f1
[2]    4923 abort (core dumped)  ipython
```

Is this a bug in pycapnp or is my schema invalid?

**Comment by jparyani** [comment]
`Ethernet2` is a group inside of `Protocol`, so you cannot directly create a message using it. Groups create pseudo-structs under the hood, and that's why it shows up in the module (maybe we should hide it instead?). What you probably want to do is:

```python
protocol = main_capnp.Protocol.new_message()
eth = protocol.init('ethernet2')
print eth.source
```

**Comment by little-dude** [comment]
Thank you for the answer :)

I found out afterwards that this question [was addressed in the documentation:](http://jparyani.github.io/pycapnp/quickstart.html#unions). But I don't really understand the final warning:

> Requiring the init makes it more clear that a memory allocation is occurring, and will hopefully make you mindful that you shouldn’t set more than 1 field inside of a union, else you risk a memory leak

I understand that memory is allocated, but where is the risk of memory leak here, exactly?

**Comment by jparyani** [comment]
The reason for this is slightly confusing and probably deserves its own section in the docs. Essentially, Cap'n Proto messages are stored in memory in serialized format, and it uses an arena allocator without garbage collection for complex datatypes. This means whenever you set/init a field that is non-primitive (ie. not an int/float/bool), an allocation will occur. If you set that field again, the old allocation will still be present in the message, and thus "leak" into the message. This isn't a memory leak per-se, since it will go away once the whole message is deallocated but it's still very bad as it will leak into wherever you output your message. Unions are especially confusing, since multiple fields share the same part of the message, and it is easy to accidentally overwrite and leak a field.

See https://github.com/jparyani/pycapnp/issues/18#issuecomment-26693337 for a discussion by the creator Cap'n Proto on this issue.
