### ISSUE TITLE
Please add tags for the official recent releases

### ISSUE THREAD

**Issue by vitaly-krugl** [jparyani/pycapnp#110]
I was trying to reproduce builds for several of the recent official releases, but had some trouble matching those releases to commits in the repo. The latest tag in the repo is for v0.5.6, and the tags for subsequent releases are absent.

**Comment by jparyani** [comment]
Oh it's my bad, I've been forgetting to push with `git push --tags` recently. Fixed now.

**Comment by vitaly-krugl** [comment]
Many thanks!
