### ISSUE TITLE
unwanted warning when writing a message twice

### ISSUE THREAD

**Issue by madeleine-empirical** [jparyani/pycapnp#111]
I have a message `m`. I want to write `m` to a file, then fill in an empty field, then write it to a different file.

When I write it the second time, I get:

> UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.

I should be okay, since the field I'm setting is unset in the first write. But, if I try to do `m._is_written = False` (or any variant with `setattr`), I get:

> AttributeError: src/capnp/schema.c++:482: failed: struct has no such member; name = _is_written

...which makes sense, since `__setattr__` is overridden [here](https://github.com/jparyani/pycapnp/blob/d85200cee34653b6df8b2c8484a6f541f66a8ddd/capnp/lib/capnp.pyx#L1251).

Any ideas? Thanks.

**Comment by jparyani** [comment]
Sorry, this was an oversight :)

I added a `clear_write_flag` method. Can you try it out (eg. `pip install https://github.com/jparyani/pycapnp/archive/develop.zip`) and let me know how it works for you?

**Comment by madeleine-empirical** [comment]
That works. Thanks!

**Comment by zaibon** [comment]
Is this fix already available in the version we get when installing using pip ? Cause I don't find the clear_write_flag method.  Installing with `pip install https://github.com/jparyani/pycapnp/archive/develop.zip` indeed bring the fix but I would prefer not to have to install the lib using this URL

**Comment by jparyani** [comment]
Fix is now deployed to pypi as v0.5.10
