### ISSUE TITLE
No way of setting ReaderOptions on an TwoPartyClient?

### ISSUE THREAD

**Issue by asilversempirical** [jparyani/pycapnp#125]
We have some very large RPC responses, and we're hitting the traversal limit when receiving the response in pycapnp. I looked at how to pass ReaderOptions down to the client, but it looks like it's currently impossible.

This was discussed on the C++ side in https://groups.google.com/forum/#!searchin/capnproto/readeroptions%7Csort:relevance/capnproto/kKSyOqm7ASM/3NkUYGoAFz0J and implemented in https://github.com/sandstorm-io/capnproto/pull/120/files.

It looks like in order to do the same thing on the pycapnp side we'd just have to pipe a ReaderOptions  from the TwoPartyClient down to https://github.com/jparyani/pycapnp/blob/468375d5667ffc3c51c9f6aed4bc083822a2f470/capnp/includes/capnp_cpp.pxd#L48.

Would you accept a PR that did so? Am I missing a way that this is already possible?

Thanks!

**Comment by jparyani** [comment]
It's not possible at the moment, but I'd be happy to accept a PR adding such functionality.

**Comment by asilversempirical** [comment]
This is worsened by https://github.com/sandstorm-io/capnproto/issues/407 and the fact that if your client and server have different limits bad things can happen.
