### ISSUE TITLE
release 0.5.10 available via pypi but not github

### ISSUE THREAD

**Issue by chaoflow** [jparyani/pycapnp#138]
- https://pypi.python.org/pypi/pycapnp/0.5.10
- https://github.com/jparyani/pycapnp/releases

**Comment by lannybroo** [comment]
Agreed this is confusing. I don't find the changes that are in 0.5.10 on pypi in the github repo (for example, CHANGELOG.md does not have the new content from pypi). Guessing there is a missing changeset that needs pushed to github. As of today, conda-forge/pycapnp-feedstock#6 also points at 0.5.10.

**Comment by jparyani** [comment]
Yep, my bad. Should be fixed now (although the history got a bit weird because I forgot to push it before merging some recent PRs).
