### ISSUE TITLE
confusing behavior when field is named "schema"

### ISSUE THREAD

**Issue by madeleine-empirical** [jparyani/pycapnp#144]
If I understand correctly, "schema" is not a reserved word in capnproto schema files. However, it has a special meaning in pycapnp. Is there an idiomatic way to access fields named "schema" without resorting to `to_dict`?

Here's a strangely-behaving python script. 

```python
from tempfile import NamedTemporaryFile
import capnp

SCHEMA = b'''
@0x9ae8e764f07b1c27;

struct Message {
  notSchema @0 :Int32;
  schema @1 :Int32;
}

const test :Message = (notSchema = 1, schema = 2);
'''

with NamedTemporaryFile(suffix='.capnp') as tmp:
    tmp.write(SCHEMA)
    tmp.flush()
    schema_schema = capnp.load(tmp.name)
    print('test:', schema_schema.test)
    print('test.notSchema:', schema_schema.test.notSchema)
    print('test.schema:', schema_schema.test.schema)
```

Here is its output:

```
test: (notSchema = 1, schema = 2)
test.notSchema: 1
test.schema: <schema for tmpsuhzlq3o.capnp:Message>
```

Until I read the source, I would've expected this output:

```
test: (notSchema = 1, schema = 2)
test.notSchema: 1
test.schema: 2
```

...but when I explicitly access my "schema" field, I get the special behavior.

**Comment by jparyani** [comment]
Ya, unfortunately `schema` is a reserved keyword for pycapnp. There's a handful of others too (like `adopt`, `write`, etc.). Would it have helped you if pycapnp printed a warning when loading such a schema?

To workaround this, you'll have to use the `_get` and `_set` methods. Even though they begin with underscores, they are "public" in the sense that I won't ever remove them, and I really should add docs about them. They're methods of last resort for conflicts such as this.

**Comment by madeleine-empirical** [comment]
Even though it would've saved me some time, I'd rather not have a warning. In my case, I've kept the field name and gotten the code to work with `_get`. (Thanks!) A warning would just confuse users now that the code works.

**Comment by jparyani** [comment]
You'd have to suppress them using https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings. Obviously non-ideal, so I guess I'll hold off until more people complain :)
