### ISSUE TITLE
Odd permission denied error during pip installation

### ISSUE THREAD

**Issue by scottpurdy** [jparyani/pycapnp#38]
The capnp-bundling installation is working great for our project but we had a report by a user of a failure. You can see the details at numenta/nupic#1719. It appears that when pycapnp detects capnp is not installed and attempts to download it, there is a permission denied error for the download location. I looked at the pycapnp scripts and they seem to be properly making the target directory so I am not sure where it goes wrong.

Interestingly, manually pip installing pycapnp seemed to work for this user so I think it may be linked to pip installing in "editable" mode (`pip install -e` or `python setup.py develop`). So perhaps this is a problem in our project rather than pycapnp but hoping you have some insight into it.

**Comment by jparyani** [comment]
Unfortunately I'm having trouble reproducing this. I did the following on a debian jessie box:

```bash
git clone https://github.com/numenta/nupic.git && cd nupic
pip install --allow-all-external --allow-unverified PIL --allow-unverified psutil -r external/common/requirements.txt
yes | pip uninstall pycapnp
python setup.py develop
```

Were you able to see this error yourself? Maybe @breznak can shed some light on how he's hitting this problem.

**Comment by scottpurdy** [comment]
I wasn't able to reproduce on OS X or an Ubuntu instance either. @breznak?

**Comment by scottpurdy** [comment]
I think this is fine to close since we can't reproduce. If I can reproduce in my project I will debug further.

**Comment by david-ragazzi** [comment]
@breznak @rhyolight @scottpurdy I'm presenting the same issue when try install NuPIC in the recent created Travis file for NuPIC Studio (https://travis-ci.org/nupic-community/nupic.studio/jobs/55951689#L188). I'm having to install pycapnp manually using pip (https://github.com/nupic-community/nupic.studio/blob/update_dependencies/ci/travis/install-linux.sh#L10).

**Comment by david-ragazzi** [comment]
It seems that this can solve:

https://github.com/jparyani/pycapnp#common-problems

**Comment by rhyolight** [comment]
Ah, good catch, @david-ragazzi!

**Comment by david-ragazzi** [comment]
Another alternative is use:

```
git clone https://github.com/jparyani/pycapnp.git
pip install --install-option '--force-cython' ./pycapnp
```
