### ISSUE TITLE
Generate PyPy native bindings using Reflex

### ISSUE THREAD

**Issue by thedrow** [jparyani/pycapnp#41]
This project currently uses Cython. Cython on PyPy uses cpyext which causes the extension to run slower on PyPy in comparision to CPython.
PyPy has a native C++ interface called [cppyy](http://pypy.readthedocs.org/en/latest/cppyy.html).
It uses Reflex to automatically generate the bindings from Python to C++ code.
I already succeeded in generating PyPy bindings (blog post coming soon) for Protobuf using cppyy so I'm willing to help to make this happen.
The backend will be selected according to the interpreter.

What do you think?

**Comment by jparyani** [comment]
I had no idea about cppyy/Reflex and both look very cool.

Unfortunately pycapnp uses an embarrassingly large amount of cython code and I'm not sure how re-usable it would be with Reflex. It's looking to me like it would almost be better to start over completely from scratch, but I'm not sure. Also, I don't use pypy so I'm not very motivated to work on this, but I'm more than happy to accept any PRs adding this kind of functionality :)

**Comment by thedrow** [comment]
You'd be starting your C++ binding code from scratch but not the Python code.
The first step is to try to abstract the binding backend.

p.s.
PyPy is awesome and it's getting better with each passing day.
You should try it.

**Comment by jparyani** [comment]
For better or worse, much of the logic of pycapnp is written in Cython and does use Cython features. There's not much actual Python code in libcapnp. This of course speeds things up for CPython, but is disadvantageous for PyPy

I've been meaning to switch over to PyPy, but every time I try I always hit a wall with a package I really want not being ported. The lack of numpy/pandas is really killer for me.

**Comment by thedrow** [comment]
Then I urge you to donate to PyPy's NumPy project. Every dollar helps :)

**Comment by Downchuck** [comment]
@jparyani Can this issue be closed? This is indeed a cython-oriented project.

**Comment by jparyani** [comment]
Agreed, closing. A cppyy version of pycapnp would be awesome, but I imagine it would be a separate project. A pure-python version would probably be good enough for pypy too.
