### ISSUE TITLE
Build does not report coverage

### ISSUE THREAD

**Issue by thedrow** [jparyani/pycapnp#42]
Can you please activate coveralls.io so that coverage would be tracked over time?

**Comment by jparyani** [comment]
Unfortunately, from my understanding there is no good coverage testing tool for cython, and unfortunately the bulk of pycapnp is written in cython. Adding coveralls would only check the __init__.py/setup.py/scripts.

For reference, some people on larger projects seem to be talking about adding coverage testing for cython:
https://groups.google.com/forum/#!msg/scikit-image/I79s8VXxdXc/yES7a3qNZHMJ
http://mail.scipy.org/pipermail/numpy-discussion/2014-August/070949.html

Closing this. Feel free to re-open if you find a solution.

**Comment by thedrow** [comment]
I learned something new. Thanks!
I will reopen if this is ever resolved.
