### ISSUE TITLE
Exception on import (enum type creation)

### ISSUE THREAD

**Issue by davidcarne** [jparyani/pycapnp#57]
With capnp-{v0.5.0,v0.5.1,master}, and pycapnp-{v0.5.1,v0.5.0,develop} I get an error during `import capnp`. 

Specifically:

```python
>>> import capnp
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  /usr/include/capnp/schema.h:840: failed: expected primitive != schema::Type::STRUCT && primitive != schema::Type::ENUM && primitive != schema::Type::INTERFACE && primitive != schema::Type::LIST
 ...
Aborted
```

Removing initializing `types.Enum` in capnp.pyx seems to solve the issue. Specifically, constructing a bare `Type` of `schema::Type::ENUM` doesn't seem to be supported by capnproto; rather it wants a concrete Enum. This hasn't been supported since  https://github.com/sandstorm-io/capnproto/commit/87ea5bdb04a02bfb0b09c40be55eb6524030333c#diff-93583ef7e9c5c392dc4f12098e0a8859R724 . I'm actually sorta confused as to how it ever worked.... maybe pycapnp has never been tested with a debug build of capnproto?

A trivial patch (https://gist.github.com/davidcarne/67da9b89e64067a21354) at least allows the import. 

With that patch, `addressbook.py` works, but `calculator_client.py` doesn't seem to. That's probably another issue....

**Comment by jparyani** [comment]
Hmm that's interesting since it's tested against C++ Cap'n Proto v0.5.2 and master and both seem to be working fine. What version of C++ Cap'n Proto do you have installed? What's your OS/architecture?

Separately, can you try `yes | pip uninstall pycapnp; pip install --install-option '--force-bundled-libcapnp' pycapnp` to see if it fixes your problem?

**Comment by jparyani** [comment]
Oh sorry, I see now that you tried multiple version of libcapnp. Still, try the pip install with the `force-bundle-libcapnp` to see if it fixes it.

**Comment by davidcarne** [comment]
OS=linux/gentoo , Architecture=amd64

Using `pip install --install-option '--force-bundled-libcapnp' pycapnp` works, but the issue may worth a deeper look: I think the use of `-O2 -NDEBUG` in `buildutils/build.py` is masking a potential bug.

Just removing the `-O2 -NDEBUG` flags from the environ CXXFLAGS (in `buildutils/build.py`) causes the same behaviour mentioned above. If forcibly disabling the capnproto assertions is intentionally required for pycapnp rather than just as a speed optimization, please let me know and I'll close this issue (and then just force -NDEBUG in my ebuild).

In detail, the assertion/exception that triggers for me for hand-builds is `KJ_IREQUIRE`. `KJ_IREQUIRE` is only defined as something other than a noop when `KJ_DEBUG` is defined. `bundled/capnproto-c++/src/kj/common.h` define `KJ_DEBUG` (and therefore `KJ_IREQUIRE`) only for builds where no optimization level is specified, and where NDEBUG is not specified.

**Comment by jparyani** [comment]
Ah ok, sorry, I didn't quite understand at first that it was due to you running a DEBUG build. It's been a while since I've tested pycapnp with a DEBUG build, but it's certainly intended to be working :)

I'll start on getting it working, and I'll add it to travisci so this doesn't diverge again.

**Comment by davidcarne** [comment]
Also, for what its worth, I think the way `-O2 -NDEBUG` is set in `buildutils/build.py` causes a difference in the `CXXFLAGS` for how pycapnp is built depending on whether a system capnproto is present

- without system capnproto: both capnproto + pycapnp are built with `-O2 -NDEBUG ${CXXFLAGS}`
- with system capnproto: pycapnp is built with system `CXXFLAGS`

**Comment by jparyani** [comment]
Good catch, I'll fix that as well.

**Comment by jparyani** [comment]
Ok this is fixed, and now being tested by travis, so hopefully I won't miss these sorts of issues again.

I'm not sure what the issue you're seeing with the calculator example is. Can you try running `pip install pytest` and `py.test test` from the pycapnp source directory?
