### ISSUE TITLE
warnings during python build

### ISSUE THREAD

**Issue by jparyani** [jparyani/pycapnp#71]
Reported originally by @glycerine on https://github.com/sandstorm-io/capnproto/issues/217.

>With recent capnproto c++ sources, On Centos6.6 amd64, I get a bunch of compiler warnings when installing the python bindings. I'm not sure if these are really warning about anything real, but it would be preferred to quiet them if possible.

**Comment by jparyani** [comment]
My response on the previous thread was:

>The main deprecation warnings are due to wrapping some old methods for bootstrapping capabilities. I'm worried a lot of code has been written using the old methods, and won't be removing this until it's removed upstream.
>
>The `get_dependency` deprecated functions will definitely be removed in the v0.6.0 release as I've had a warning about it for a while now.

**Comment by Downchuck** [comment]
@jparyani Warnings seem pretty common during cython builds, suggest closing this issue.
