### ISSUE TITLE
Import hooks not working with .egg distribution

### ISSUE THREAD

**Issue by scottpurdy** [jparyani/pycapnp#72]
We are using the import hooks to import our capnp schema files. This works fine for most installation/distribution methods, including editable/developer installs and wheel files. But eggs fail to import the capnp file. I am suspicious that it is because .egg files have a SOURCES.txt that lists all of the source files in the package and the import (blah_capnp) doesn't match the filename (blah.capnp).

Is this a limitation of the import hook or do we have our egg files set up incorrectly?

**Comment by jparyani** [comment]
Can you point me to an example .egg and I'll take a look. I'm not sure what's causing the problem here.

**Comment by scottpurdy** [comment]
One of the 0.2.5 eggs here:
https://pypi.python.org/pypi/nupic

I tried switching to the explicit `capnp.load` call and using `pkg_resources.resource_filename` to find the file path and that works but then I get an error when a schema attempts to import another schema. I printed out the pkg_resources path and it was something like this:

`/Users/me/.python-eggs/package.egg-tmp/path/to/file.capnp`

And when I look in that path, there are only a few files present. So I think since a .egg file is really a zip archive that it unpacks the files that need to be directly accessed.

I am sure there is a idiomatic way to make this work but I can't figure out what it is. I will keep digging around now that I understand what is going on a little better.

**Comment by scottpurdy** [comment]
I think I found the issue here:
http://stackoverflow.com/questions/2798451/python-why-do-some-packages-get-installed-as-eggs-and-some-as-egg-folders

Let me confirm and I will follow up.

**Comment by scottpurdy** [comment]
Yes, it looks like regardless of the import mechanism, pycapnp requires the .egg archive be made with the "zip_safe" options set to `False` in the `setup()` function.

**Comment by jparyani** [comment]
Cool, thanks for tracking it down :)

As long as we rely on the C++ Cap'n Proto library for importing, it will never be zip .egg aware. If we ever move to a pure python implementation or we pre-generate the python schemas, then we can revisit this.

**Comment by scottpurdy** [comment]
@jparyani - Yes, I looked if there was a way to pregenerate the Python schema but didn't see anything. Does this exist somewhere or is it planned? Not a big deal as I think the `zip_safe=False` solution is totally fine for us but it might speed up initial start up a little.

**Comment by jparyani** [comment]
I once had plans to write a capnp cython code generator (see https://github.com/jparyani/pycapnp/blob/develop/capnp/_gen.py), but it languished. It's main purpose was to speed up field access, but it could also be useful for binary distributions.

It's only semi-functional at this point, and doesn't handle cross `.capnp` file imports.
