### ISSUE TITLE
reading from bytes?

### ISSUE THREAD

**Issue by waynenilsen** [jparyani/pycapnp#73]
The read function currently relies on `fileno` so when I tried to use an `io.BytesIO` object the result was an exception. I have capnproto messages stored in memory so I don't want to write them to disk just to read them back. Is there any way around this?

**Comment by jparyani** [comment]
I think the functions you are looking for are `from_bytes` and `to_bytes`. See https://jparyani.github.io/pycapnp/quickstart.html#byte-strings-buffers

**Comment by waynenilsen** [comment]
Yep, thanks. For some reason that wasn't immediately obvious and I just assumed ["reading a message"](https://jparyani.github.io/pycapnp/quickstart.html#read-a-message) was the only way to "read" just had to read a bit further to the "Deserializing" section
