### ISSUE TITLE
unittest assertEqual has counterintuitive results

### ISSUE THREAD

**Issue by waynenilsen** [jparyani/pycapnp#74]
the assertion below fails, seems odd

```python
self.assertEqual(
	self.interop.MessageType.Date.new_message(year=2016, month=2, day=1)
	, self.interop.MessageType.Date.new_message(year=2016, month=2, day=1)
)
```

I have already loaded a schema as follows

```capnp
@0x895ad5210a9d686d;

struct Date {
  year @0 :Int16;
  month @1 :UInt8;
  day @2 :UInt8;
}
```

**Comment by jparyani** [comment]
Unfortunately, equality operators aren't implemented yet. For now, you could do `.to_dict()` for each and compare the dicts.

**Comment by waynenilsen** [comment]
that works fine, thanks.

**Comment by haata** [comment]
Sure, though I'm not sure how quickly it'll be implemented.
