### ISSUE TITLE
pip install from github

### ISSUE THREAD

**Issue by waynenilsen** [jparyani/pycapnp#77]
I tried to install from github using `pip3 install git+https://github.com/jparyani/pycapnp@develop` but it gives an error. I made a [gist](https://gist.github.com/waynenilsen/a9932ae4cdabbe0b4c88) since the text output was too long. This is probably my fault for trying to install the package this way but i thought it might work, it would be a nice feature. 

edit: instructions from the readme give the same results

**Comment by jparyani** [comment]
It's a known issue with cython == v0.22.x. Downgrade with `pip install cython==0.21.2` to resolve the issue. There is a fix for it upstream, but it seems that it won't land until a cython v0.23 release.

**Comment by jparyani** [comment]
Actually, I just realized that the cython v0.22.1 update did fix this problem for pycapnp. Make sure you have the latest cython (pip install -U cython), and get my recent commit 3357771b393d4c4d218dfbc178e4715ca63b97da

**Comment by waynenilsen** [comment]
This worked like a charm, thanks. Apparently my cython was a bit behind. Just as an FYI, this did work for your repo `pip3 install git+https://github.com/jparyani/pycapnp@develop` and it's a pretty neat way to get the newest version.
