### ISSUE TITLE
Allow import to find capnp files that are on the python path

### ISSUE THREAD

**Issue by akhilaananthram** [jparyani/pycapnp#78]
Instead of using relative paths on the file system to import capnp files, it would be nice to also find capnp files using the python path.

**Comment by jparyani** [comment]
The import hook (ie. `import FOO_capnp`) should already work this way. If it's not working for you, it's a bug.

**Comment by akhilaananthram** [comment]
Is there an example of this somewhere? I think I'm a bit confused on the syntax.  I don't think this is a bug.
