### ISSUE TITLE
Provide option to compile .capnp to .py

### ISSUE THREAD

**Issue by scottpurdy** [jparyani/pycapnp#81]
Would it be possible to provide a compiler that generates Python code from .capnp schema and allows using pycapnp with Cap'n Proto Lite mode (a.k.a. Windows support). This would be something like `capnp compile -opy ...` and give you files that you can import without the import hook or the need to import the `capnp` package.

I don't have a pressing need for this but curious if it would help with Windows support (CAPNP_LITE).

**Comment by jparyani** [comment]
This would essentially be writing a pure python version of Cap'n Proto. It's definitely something I'd like to do at some point, and it actually shouldn't be a massive amount of work to support only serialization, but I don't have a lot of time to do it myself.

Ideally, it would be implemented as a separate library and would be a drop-in replacement for pycapnp (except for the `capnp compile -opy` step).

**Comment by scottpurdy** [comment]
Oh that makes sense, thanks for the info!
