### ISSUE TITLE
Expose reflector accessors

### ISSUE THREAD

**Issue by Downchuck** [jparyani/pycapnp#83]
Similar to these in the cprotobuf project:
https://github.com/yihuang/cprotobuf#reflection

It'd make it quite a bit easier to move between data structures.

EDIT: Example...

I am taking some protobuf data and translating it into capnproto. Translating the schema was not fun, and capnproto is very opinionated about field names, requiring me to remove underscores and switch to camel case. Otherwise I could simply use to_dict methods.

But, since I am using the same schema, essentially, all of my field offsets line up. Unfortunately, I don't see an easy way in pycapnp to set a value from the field number.

**Comment by Downchuck** [comment]
Somewhat of a workaround for my issue:
```
x = dir(a.fAddress[0])
setattr(a.fName[0], x[i], v[i+1])
```

Not that bad of a situation, just seems a little inefficient.

**Comment by Downchuck** [comment]
Closing this issue. If I find an area where performance is an issue I'll open a new one.

**Comment by jparyani** [comment]
As you found, `.schema.fieldnames` or `dir` works on pycapnp structs and `setattr` is the way to go for setting fields with strings. Another option is to use the `to_dict` function, but that's probably not any faster and is definitely more memory inefficient.

**Comment by Downchuck** [comment]
The setattr/getattr translation carries a very large cost:

```
        def doField(source, target, snartNames, transNames):
                idx = 0
                for f_names in source:
                        fNames = target[idx]
                        idx += 1
                        for kv in snartNames:
                                val = getattr(f_names, kv[1])
                                setattr(fNames, transNames[kv[0]], val)
```

That's copying an array from a protobuf struct to a capnproto struct using setattr.
I suspect that having a method to simply run:  target.setidx(kv[0], val) would be significantly faster.

**Comment by jparyani** [comment]
There is an internal method `._set` on structs that takes exactly the arguments you want. Since it's internal, I make no guarantees on stability across upgrades and would recommend against using it. 

Truthfully, I'd be very shocked if it actually caused much of a performance improvement.

**Comment by Downchuck** [comment]
I want to use an integer, the id of the field.

So if __getitem__ were implemented, target[0] would be the first field.
Just as setting, target[0] = "Data" would set .

**Comment by jparyani** [comment]
Ok sorry I misunderstood you before. The Cap'n Proto C++ dynamic api on which pycapnp is built doesn't exactly support lookup by index, so I didn't want to expose it in pycapnp. What it _does_ support is lookup by a field schema, which conveniently is provided with the rest of the schema and can be used with `_set_by_field`/`_get_by_field`

The following should work:
```python
import capnp
import addressbook_capnp

p = addressbook_capnp.Person.new_message(name='test', email='test@test', id=1000)
for field in p.schema.fields_list:
  print p._get_by_field(field)
```

Same caveat as before about internal functions, and I'd highly recommend benchmarking before committing to doing it this way.

**Comment by Downchuck** [comment]
@jparyani Thank you for taking the time to walk me through this!
It's faster, but also, easier code to read.

1.8seconds for setattr, 1.3 seconds for _set_by_field.
