### ISSUE TITLE
read_multiple and read_multiple_packed are incorrect on multi-segment messages larger than 8KiB

### ISSUE THREAD

**Issue by drakedevel** [jparyani/pycapnp#87]
This code structure is problematic:

```
with open('file.bin', 'rb') as f:
    for obj in Msg.read_multiple(f):
        pass
```

The first message `obj` doesn't get deleted until after the second `read_multiple` call completes. This means that the underlying `InputStreamMessageReader` doesn't get destructed prior to the next one being initialized. The destructor for `InputStreamMessageReader` is responsible for skipping to the end of a message which hasn't been fully read (for example, because it is multi-segment and larger than the default 8192 byte buffer), so the next reader will pick up in the middle of the previous message.

This generally errors -- I've observed "Message did not contain a root pointer" and "Message has too many segments". It is not hard to construct a case that leads to no error but an incorrect interpretation of the data (which could have security implications in the presence of signed messages).

The fix is to ensure that each `InputStreamMessageReader` gets destructed prior to the next one's construction. The returned message holds a reference to the reader, so an application consuming this library can call `del obj` manually. It only is guaranteed to work by CPython implementation detail, and generally is a serious usability issue for the API. No documentation I could locate mentions this issue, and small examples work fine until the magic 8K threshold -- including the test suite.

One fix strategy is to modify `_MultipleMessageReader.__next__`: poison the previously-returned object, and force the underlying C++ `InputStreamMessageReader` to be destructed. It would fix the common case of a loop and allow for a more helpful error message if a stale object remains referenced.

This gist has an example data file and runnable samples showing the issue: https://gist.github.com/drakedevel/c270ba5c8dfa1ac568aa

**Comment by jparyani** [comment]
Thanks for reporting!

I actually went with copying messages by default in the `read_multiple*` functions. Calling delete explicitly on loop iteration would be faster, but I'm worried that people wouldn't know that, and mistakenly cache invalidated messages. I added a `skip_copy` parameter for people that know what they're doing and need performance.

**Comment by drakedevel** [comment]
Cool, that sounds like a good compromise. Thanks for the fast fix!
