### ISSUE TITLE
setup.py should use setuptools

### ISSUE THREAD

**Issue by treeandbrick** [jparyani/pycapnp#88]
`setup.py` is using `setup` from `distutils` and not `setuptools`. Because of this, options such as `install_requires` and `entry_points` are not recognized. The setuptools `setup` is a drop-in replacement.

**Comment by jparyani** [comment]
The reason for this originally was that certain versions of setuptools would cause problems with the cython part of the build. I'll test if that's still the case and/or enforce some minimum version of setuptools.

**Comment by treeandbrick** [comment]
Also, is there any interest in modifying `setup.py` to (optionally) pull cflags and library from pkg-config?

**Comment by jparyani** [comment]
I'd be happy to accept a pull request. It would have to gracefully handle pkg-config not existing and pkg-config not having a definition for capnp, since I wouldn't want to make it a hard dependency.

**Comment by treeandbrick** [comment]
Also because we are not using setuptools, we cannot build a wheel:

`error: invalid command 'bdist_wheel'`

**Comment by chaoflow** [comment]
The switch seems to have happened: https://github.com/jparyani/pycapnp/commit/0a941a9e06d2a60ae569ed6b75e25468feeb6c04

**Comment by jparyani** [comment]
Yep this is now done and released in v0.5.10
