### ISSUE TITLE
mmap patch causes process segfault with python 2.7

### ISSUE THREAD

**Issue by novas0x2a** [jparyani/pycapnp#93]
Both on my laptop and on the relevant travis build:
https://travis-ci.org/jparyani/pycapnp/jobs/107275771

Maybe a revert is in order?

**Comment by jparyani** [comment]
It turns out mmap doesn't provide a buffer interface under Python 2.x. I fixed it so it doesn't segfault and instead raises a Python exception in 2be308db2733fad08d48f87a835c38d3ea5288ec.
