### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by brunsgaard** [jparyani/pycapnp#99]
@jparyani Are these numbers expected? I am surprised that Msgpack is soo much faster than Cap'n Proto. The benchmark code is available [here](https://gist.github.com/brunsgaard/1291b8bfd02c4d0df2e706290c96ce0a) and the results below is obtained with Python 3.5.1 on FreeBSD.

```
Testing Msgpack:
build datastructure:   1097 ms
serialize:             6836 ms
deserialize:           3008 ms
totaltime:            10942 ms
size:                 72.48 MB

Testing Capnp:
build datastructure:  68327 ms
serialize:             4610 ms
deserialize:           1519 ms
totaltime:            74456 ms
size:                 70.77 MB

Testing Protobuf:
build datastructure:  59912 ms
serialize:            73065 ms
deserialize:         100671 ms
totaltime:           233649 ms
size:                 41.96 MB
```

**Comment by frol** [comment]
I guess this is related to #31.

**Comment by jparyani** [comment]
It's worth noting that msgpack is doing something very different here. It is "just" serializing a python dictionary object into essentially a binary json blob. It has no type checking, no schema defined object that you can inspect at runtime, no default values, etc. Essentially, if you added all of that stuff on, I'd expect msgpack to perform closer to pycapnp. Msgpack would probably still be faster, since they've put a ton of time and effort into optimization, whereas I've only had time to fix up the bigger slowdowns that I can find in pycapnp.

Also, worth noting a couple of speedups to pycapnp for your benchmark:
```python

import capnp
import addressbook_capnp
MOBILE_TYPE = addressbook_capnp.Person.PhoneNumber.Type.mobile # This is a number under the hood

n = 1000
addresses = addressbook_capnp.AddressBook.new_message()
people = addresses.init('people', n)
for alice in people: # you can iterate over pycapnp lists, and its actually faster than the alternative
    alice.id = 123
    alice.name = 'Alice'
    alice.email = 'alice@example.com'
    alicePhone = alice.init('phones', 1)[0] # accessing the [0] element twice is inefficient
    alicePhone.number = "555-1212"
    alicePhone.type = MOBILE_TYPE
```

**Comment by duedal** [comment]
Thank you for responding, and giving a few speedups too @jparyani. What I was wondering was how deserialization could be soo much faster than building the data structure in the first place. I was speculating that we (I work with brunsgaard) where doing something wrong.

On our modest test hardware (Xeon E5620) your speedups does bring it down 5 seconds.
```
Testing Capnp:
build datastructure:  63677 ms
serialize:             4974 ms
deserialize:           1776 ms
totaltime:            70428 ms
size:                 70.77 MB
```

**Comment by jparyani** [comment]
Cap'n Proto is a zero copy message format. What this means is that the message is built in memory as "serialized" format, and serialize/deserialize is essentially just a memcpy under the hood. Your benchmark is actually flawed in that it's not really testing the cost of accessing fields inside the deserialized message. For msgpack, it's just a dict, and for protobuf I think it's essentially a dict (not sure though). For pycapnp however, that will be where the bulk of your deserializing time will be spent.

For another perspective on how tricky it is to benchmark Cap'n Proto, see https://groups.google.com/d/msg/capnproto/Q3ivsQ467_o/vNwXKNtflrMJ

**Comment by brunsgaard** [comment]
@jparyani That makes sense ;)
